# Inventory List example 

server1.tech.local

[webservers]   # Group definition
server2.tech.local
10.0.0.1

[all:vars]   # Define variable for all groups
ansible_ssh_private_key_file= <location>
ansible_user= <user_name>
ansible_python_interpreter=/usr/bin/python3 # Select which python interpreter to use if many are installed on the client 


